### PR TITLE
set default value for serial parameter in setUpdateListener

### PR DESCRIPTION
**Pull request by adbenitez**

### CODE REVIEW

**Comment by Simon-Laux** [comment]
you can do `serial = 0` in the function signature and also do that in the ts to mark the argument as optional

**Comment by adbenitez** [comment]
will that be compatible with most browsers?

**Comment by Simon-Laux** [comment]
not in internet explorer, but the other browsers support it for some time already:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters#browser_compatibility

**Comment by adbenitez** [comment]
done

**Review by Simon-Laux — APPROVED** [review]

**Pull request merged**
